### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by nerdbeere** [james-proxy/james#1]
- [x] click in list to add URL mapping
- [x] click in list to remove URL mapping
- [ ] filter list by mapped URLs
- [ ] showing mapping when mouseover "mapped" tag
- [ ] block URLs
- [x] HTTPs Support (See https://github.com/greim/hoxy/issues/4)
- [x] Better design for adding mappings

**Comment by sholladay** [comment]
This is a very cool project, @nerdbeere. Could you put together a contribution guide with some recommendations for how to help out?

**Comment by nerdbeere** [comment]
thanks @sholladay! I have a big branch that I will merge in the next days containing big improvements for rendering requests. After that I will add tests and eslint. Then this project is at a point where others can start contributing.

**Comment by nerdbeere** [comment]
@sholladay I added tests, linting and a automated build process. Feel free to contribute.

**Comment by sholladay** [comment]
Fantastic, this could potentially compete very well with an internal tool my team has built on top of hoxy that only does an "OK" job at replacing Charles. Our main use case involves manipulating the script tag of our JavaScript library. So that means we need an equivalent to the Tools -> Rewrite section of Charles.

**Comment by nerdbeere** [comment]
I will look into that feature. Could you elaborate on your use case? That would be helpful.

**Comment by sholladay** [comment]
Sure. So our customers put a loader into their pages in a similar fashion to [Google Analytics](https://developers.google.com/analytics/devguides/collection/gajs/#tracking-code-quickstart).

````html
<script data-provider="myProduct">
var myProduct = myProduct || {};
// .... configuration, etc. ...
(function () {
    var script = document.createElement('script');
    // ... actually load the JS library ...
}());
</script>
````

Among other things, that loader script contains info about where to fetch the JS library from, which is different for production vs development and when in development, which git branch to use, etc. (we deploy all of them).

Sometimes we need to strip off the loader on a customer's live site and replace it with a loader configured for development (to test an upcoming version for regressions, etc). That's the main use case.

Charles lets us do this with a GUI via its Rewrite tool, but it only accepts clumsy regex operations. Hoxy allows nice, clean CSS lookups with its `as` intercepts. We've been itching to build something nice around that. But this seems like the right place for it. Basically, it would provide a means of adding, removing, or replacing elements on the page.

**Comment by mitchhentges** [comment]
I've split this into several smaller issues so that this one can be closed.
And for `sholladay`'s feature: I think that issue #132 describes it nicely :)
