### ISSUE TITLE
F12 and CTRL-SHIFT-I should open the Developer Tools (like Chrome)

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#104]
Right now, the "Developer" button needs to actually be pressed. That's no fun :wink:

**Comment by nerdbeere** [comment]
on OSX it's ALT+CMD+J

**Comment by mitchhentges** [comment]
wat?

**Comment by mitchhentges** [comment]
Hmm, on OSX, it looks like `ALT+CMD+I` works too. I'll add both shortcuts
