### ISSUE TITLE
Materialize

### ISSUE THREAD

**Issue by tomitm** [james-proxy/james#106]
Curious about what the deal with Materialize is... it's an external resource, but it's also not very used very much at the moment.

It does look like it's possible to include it via npm and add it to the build. So if you're interested in making more use of it, I'd be happy to submit a PR to make James a bit more material.

Otherwise, if you want to keep the current look, it's possible to pull out that dependency and don't need to depend on being online. Lemme know which direction you'd like to go in.

**Comment by mitchhentges** [comment]
I'd personally be a fan of making it more material-y, Burt is leave the say up to nerdbeere, since it's his project

**Comment by mitchhentges** [comment]
But I'd* leave the say. Thanks mobile, I'll edit my comment in the morning

**Comment by tomitm** [comment]
Just to give you a slight idea of what that might look like...

![image](https://cloud.githubusercontent.com/assets/4513759/12800440/c595f672-ca89-11e5-8abb-9de0164fdb4d.png)

I'm trying to figure out some options for URL mappings, hence why I'm asking about material. I'm not sure if @nerdbeere's intention of adding Materialize was just for a quick prototype, or to actually end up with something material-ish.

**Comment by kokarn** [comment]
+1 for more material because that looks like the bees knees.
Also making it work "offline" should probably be what you want for this
kind of thing.

**Comment by nerdbeere** [comment]
I really like it.
I initially used it just for a quick protoype but I like how it looks.

**Comment by tomitm** [comment]
Sounds good, I'll start working on materializing then.

I'll close this since this was mainly a question about direction. Thanks!
