### ISSUE TITLE
Inspect-details is overlapping footer

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#117]
![screenshot from 2016-02-06 16-51-43](https://cloud.githubusercontent.com/assets/7784737/12867706/f097331e-ccf4-11e5-82fd-94397ae330b1.png)
Also, [Aseprite] (http://www.aseprite.org/) is _awesome_. I think that it's my new "Paint.NET"

**Comment by tomitm** [comment]
Not just overlapping, but the scrolling is broken too. Regression from #108, fixed in #117.
