### ISSUE TITLE
Start using Redux

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#136]
See the [Flux GitHub project](https://github.com/christianalfoni/flux-react)

**Comment by mitchhentges** [comment]
Aww snap, GitHub assignees! What up

**Comment by davidneat** [comment]
Maybe http://redux.js.org/ might be also an option. What are your opinions?

**Comment by mitchhentges** [comment]
I'm personally indifferent. In our [Matrix channel](https://vector.im/beta/#/room/#james:matrix.org) discussions, it seems like Redux is the better one.
I haven't used either, but I know that we need _something_, because data-passing-around is pretty sad right now in James

**Comment by kokarn** [comment]
Tried Flux, Redux and Reflux. Would go with Redux today.

**Comment by tomitm** [comment]
Redux is what I originally had in mind, as it keeps thing simple. I'm working on a prototype app for something at the moment to get the hang of it.

`proxy` will probably need some refactoring (immutability) if we want to put requests in the Redux store. Shouldn't be too bad.

**Comment by tomitm** [comment]
This is just about completed under #183, if anyone is interested in taking a look!

**Comment by tomitm** [comment]
Completed in #183! 😃
