### ISSUE TITLE
Inform users with an outdated version about the latest release

### ISSUE THREAD

**Issue by davidspinat** [james-proxy/james#139]
It would be nice to inform users about the latest available release version. Users with a packaged version may see a notification about a newer build.

I would like to use the following api endpoint to check if the user has an outdated version: https://api.github.com/repos/james-proxy/james/releases Maybe it would be also nice to provide a direct download link to the latest package.

**Comment by tomitm** [comment]
Better yet... auto-update? :grinning:

**Comment by davidneat** [comment]
Unfortunately neither https://github.com/EvolveLabs/electron-updater nor http://electron.atom.io/docs/v0.34.0/api/auto-updater/ seem to fit our current needs.

The `electron-updater` would need a running sever which provides an api with the correct `Squirrel schema`. The `auto-updater` depends on `npm packages`, which we might also publish using a private server or using the usual npm server. Tough I like the idea to seperate James into small npm packages. What is your opinion?

**Comment by tomitm** [comment]
Interesting, npm could work, but ideally if we can keep using just GitHub releases, less to maintain...

https://github.com/jenslind/electron-gh-releases

This one [looks](https://github.com/jenslind/electron-gh-releases/blob/master/docs/2.x/how-to.md) like it requires minimal changes, just a new `auto_updater.json` file for OSX updates.

Can probably use a `postrelease` npm script so we can just call `npm release` to make it easy to manage updates.

Hopefully that makes sense, haven't looked at it too closely yet.

**Comment by mitchhentges** [comment]
With #343 merged, users are now notified about new versions of James (and have the ability to auto-update)
