### ISSUE TITLE
Browser list icons not aligned properly

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#141]
Maybe it's because `browser-launcher2` is only detecting one browser? At any rate, our CSS isn't properly handling the browser list for me.
![1456349649](https://cloud.githubusercontent.com/assets/7784737/13301802/0c06e602-db47-11e5-818f-8f316154e2e2.png)

**Comment by tomitm** [comment]
Seems to be missing the version, interesting. Might be why.

**Comment by tomitm** [comment]
The objective of #91 was to display addition information, such as the version number. For whatever reason, that doesn't seem to be getting picked up in Linux, even though looking at browserlauncher2's detect code, it seems like it should've been getting picked up.

I'll spin up the ol' Linux VM later tonight and see if I can reproduce.

Ideally, I want the version number to be displayed, but if I can't resolve that for whatever reason, I'll make sure to fall back gracefully and align everything properly. Didn't realise this would be a problem originally.

**Comment by mitchhentges** [comment]
Hmm, looks like the version isn't being detected on (my) Linux box due to a race condition in `browser-launcher2`. It's detecting browser versions via `$browser --version`, and scoops the version via a fancy regex.

However, it thinks that the process is done on process `exit`. However, `stdout` isn't fully flushed on `exit`, and `browser-launcher2` should wait for process `close`. See [detect.js](https://github.com/benderjs/browser-launcher2/blob/master/lib/detect.js#L137).

Thanks @tomitm for the teamwork in solving this

**Comment by mitchhentges** [comment]
Created issue https://github.com/benderjs/browser-launcher2/issues/51

**Comment by tomitm** [comment]
Alright, got the heights fixed up, that should fix this issue. As for the other half of this issue, I've created #146 to track it.

**Comment by mitchhentges** [comment]
Awesome, thanks, Tomi!
