### ISSUE TITLE
Blank page after starting `James.app`

### ISSUE THREAD

**Issue by wolframkriesing** [james-proxy/james#150]
I downloaded the latest version 0.36.5 the `version` file says.
I double-clicked the James.app file and only get a blank screen. 
I am (still) using Mac OS 10.10.5

Running it via `npm start` works as expected though, so it might be the build.

**Comment by mitchhentges** [comment]
Perhaps you mean [version 1.4.2](https://github.com/james-proxy/james/releases) instead? `0.36.5` is the version of "Electron" that we're using.

Either way, booting up my Mac now. Thanks for the report!

**Comment by mitchhentges** [comment]
I'm able to reproduce. Thanks again, `1.4.3` should be out later today

**Comment by nerdbeere** [comment]
Hey Wolfram, thanks for the report.

The issue here is that the path to the `index.html` is wrong (currently `/home/cactipus/dev/james/build`).
This happens because browserify resolves `__dirname` during build time which is bad for us.

**Comment by mitchhentges** [comment]
`v1.4.3` is out! https://github.com/james-proxy/james/releases/tag/v1.4.3
