### ISSUE TITLE
James on Windows doesn't detect browsers ... but only in PROD

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#174]
When James is run on Windows, it doesn't show any browsers in the browser list. However, this only occurs after being `npm run package`'d. When run using `npm start`, everything is OK.

__To reproduce:__
1. Start Windows (7 or 10 confirmed)
2. `npm run package`
3. Start the windows build in`binaries`. Both the 32bit and 64bit builds are affected

**Comment by tomitm** [comment]
Testing out our release packages...

version | result
----- | -----
1.4.1 | :white_check_mark:
1.4.2 | :x:*
1.4.3 | :x:
1.4.4 | :x: 

\* 1.4.2 must have an exception, as I'm not seeing any UI at all, just white. .3 and .4 both load properly, but are missing browsers.

:confused:

**Comment by tomitm** [comment]
Alright, now that I managed to figure out 1.4.2 didn't have the issue, it looks like the problem was introduced in 1.4.3.

We had forked `browser-launcher2`, and updated `win-detect-browsers`, which was originally at 1.0.2, now 2.1.0

**Comment by mitchhentges** [comment]
This will be solved by downgrading `win-detect-browsers` to `1.0.2` in `james-browser-launcher`, then using that newer version of `james-browser-launcher`

**Comment by tomitm** [comment]
Yep, verified that rolling back `win-detect-browsers` works out. :+1:

**Comment by tomitm** [comment]
Fixed in `1.4.5`.
