### ISSUE TITLE
HTTPS isn't being enabled

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#221]
Even when the necessary certificates are generated, the proxy doesn't try to proxy secure requests.

Originally reported by @jariangibson

**Comment by mitchhentges** [comment]
@jariangibson should be fixed in [v1.5.0](https://github.com/james-proxy/james/releases/tag/v1.5.0)
TravisCI will add the downloads as the builds complete

**Comment by jariangibson** [comment]
Great! Thanks!

**Comment by jariangibson** [comment]
works like a charm!
