### ISSUE TITLE
Read HTTPS certificates from `userData`

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#222]
Before, when there wasn't an installer, the certificates would just go in the same directory as James itself. Now that is in an "installable", it should go in the "userData" folder instead.

See [how we store `nedb` for details](https://github.com/james-proxy/james/blob/2da4fbc425414628f2470b03d23f6f307c7b68f6/src/index.js#L32)
* Linux: `$HOME/.config/james/`
* Mac: `$HOME/.config/james/`
* Windows: `$HOME/AppData/Roaming/james/`

**Comment by tomitm** [comment]
Fixed in #224.
