### ISSUE TITLE
npm install gets stuck 

### ISSUE THREAD

**Issue by abhagupta** [james-proxy/james#265]
Hi,
I am trying to run `npm install` on fresh cloned repo and everytime, the installation gets stuck right after this message 

```
> node-sass@3.8.0 install /Users/agupt13/Documents/workspace/mocks/experiments/james/node_modules/node-sass
> node scripts/install.js
```
I am on node version 6.3.1. npm version 3.10.6

**Comment by mitchhentges** [comment]
Hmm, taking a look at the [`node-sass` issue list](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20install), there doesn't seem to be anything about installation getting stuck.

I just manually re-installed from scratch today, and it seems to be working.
Try deleting `~/.npm` and `node_modules` and re-do `npm install`?
Maybe it's OSX-specific: @nerdbeere, able to have a look?

**Comment by tomitm** [comment]
@abhagupta 👋 Are you still having trouble?

I'd suggest using `npm install --loglevel verbose` which will give you more information about what's going on.

Other than that, this appears to be either a `npm` or `node-sass` issue. I'm going to close this issue, as there's nothing really we can do in James to fix this for you.

However, feel free to reply with the verbose output from above, and maybe there's something hiding in there that will help me point you in the right direction. 😄
