### ISSUE TITLE
Provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [james-proxy/james#277]
It would be great if you could provide an [AppImage](http://appimage.org) for Linux. It is supported by electron-builder.

**Comment by mitchhentges** [comment]
Hmm, good point. We'll probably release an `AppImage` on our next release.

I wonder if releasing a `.deb` will still have any value, once an `AppImage` is released, hmm.

**Comment by probonopd** [comment]
Why not release both, they serve different purposes.

**Comment by tomitm** [comment]
@probonopd This'll be available in the next release! 🚀

Thanks for pointing it out!

**Comment by probonopd** [comment]
Unfortunately an [AppImage](http://appimage.org/) is still missing from GitHub Releases.

Providing one would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by tomitm** [comment]
@probonopd We just momentarily regressed on that while preparing for our 2.0.0 release - our Linux build got lost momentarily and was restored in #352.

The AppImage should be showing up in [the latest beta release](https://github.com/james-proxy/james/releases) now. _Caution: we're currently testing auto-updates, so a second beta will be landing tonight._

![image](https://user-images.githubusercontent.com/4513759/34448591-dfcb914e-ecbc-11e7-818d-931591799200.png)

**Comment by tomitm** [comment]
Also, just realised this commit landed after 1.5.0 and we haven't had a release until now. Sorry about the long lapse there, but don't worry, we definitely didn't mean to leave this out!

**Comment by probonopd** [comment]
Thank you for the update @tomitm
