### ISSUE TITLE
Unable to select file in URL Mappings Menu

### ISSUE THREAD

**Issue by TwR-Slice** [james-proxy/james#329]
OS X 10.11.6
James: 1.5.0

When I try to select a file nothing happens. Dragging a file onto the field results in the file being shown (sourcecode)
![bildschirmfoto 2017-05-08 um 10 23 31](https://cloud.githubusercontent.com/assets/14914344/25796068/69c75aca-33d8-11e7-9ddb-cb5335af06aa.png)

**Comment by mitchhentges** [comment]
Confirmed this exists on Windows, too. We have some pending infrastructure changes (the proxy now doesn't run on the UI thread) and bug fixes, which we've been holding off on until we set up auto-update.
I'll have time to push out a release this June (spending a month doing open-source shenanigans), and I'll make sure that this gets resolved.
Thanks for the report! :100: :chicken:

**Comment by tomitm** [comment]
Had a quick look... seems like the click handler is no longer triggering on the disabled text input. Not entirely sure _why_ this changed though, as even though it's been a while, I'm pretty sure it worked earlier. 🤔

Will need to change how that input works, I guess. 🕵️
