### ISSUE TITLE
Copy and Paste are not available on "Create new URL Mapping"

### ISSUE THREAD

**Issue by joelee** [james-proxy/james#334]
Tested on **macOS Sierra, Node v8.4.0, NPM v5.3.0**
Commit: f604f7a - Tue, 6 Jun 2017 18:28:03 +0200

**Steps to reproduce:**
1. Clone / npm install / npm run build / npm start
2. Copy an url from an external text editor (via cmd-C, or Edit/Copy)
3. On James Proxy, click on Mapping, click on 'Enter target URL to map'
4. Press cmd-V : nothing happens
5. Right click on 'Enter target URL to map' : no shortcut menu

**Expected result:**
When (4) pressing cmd-V, the copied URL should be paste into the text box.

**Comment by mitchhentges** [comment]
I'll take a look into this tonight, thanks for the report!

**Comment by mitchhentges** [comment]
Just looked into this, I can reproduce the context menu not popping up on any of the platforms.
However, I _can_ paste on Linux (and @tomitm confirms pasting works on Windows). I saw how Mac won't paste at all, though.

Will set up a fix tomorrow
