### ISSUE TITLE
Cannot Choose File

### ISSUE THREAD

**Issue by djbreen7** [james-proxy/james#342]
OS: Windows 10
Browser: Chrome (latest stable)

When I attempt to add a mapping as URL to FILE, I am unable to choose a file. Clicking Choose file does nothing.

**Comment by mitchhentges** [comment]
Thanks for the report!
IIRC this is fixed, but unreleased (@tomitm?).
We need to do a release soon!

**Comment by nerdbeere** [comment]
@mitchhentges is there any blocker that would prevent an update? Builds for macOS should work again.

**Comment by mitchhentges** [comment]
It would be ideal to have auto-updates working before our next release - our Sentry server gets blasted by dozens of "error" events per day of a super-out-of-date James haha.

Nerdbeere, are you available in the next couple days to hop on Matrix and spend a couple hours getting code signing working?
I might be able to shake down some guys at my work for a developer ID certificate, but it would be ideal to use the James dev's cert, if you've got time :smile:

**Comment by tomitm** [comment]
Confirmed this is working under Windows 10 in the upcoming 2.0 release.
