### ISSUE TITLE
When browser opened from "Home", requests are shown, but titlebar doesn't update

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#348]
![img](https://user-images.githubusercontent.com/7784737/34446056-1d447c78-ec8d-11e7-8d48-6c405f423b5d.png)

Note how "Home" still has the red underline, despite how the panel is showing requests.

*To reproduce:*
1. Start James
2. Click Chrome
* When requests start arriving, the main panel will change to show the requests, but the titlebar will still show "Home" as the active panel

*Acceptance criteria:*
* When a browser is selected:
  * Change panel to show requests being made
  * Update titlebar to show that "Requests" panel is now active

**Comment by tomitm** [comment]
Confirmed this is only an issue on Linux and macOS - cannot reproduce on Windows.

Interesting. 🤔
