### ISSUE TITLE
2.0.0

### ISSUE THREAD

**Issue by tomitm** [james-proxy/james#355]
Todo:
- [x] Figure out how the GitHub auto release upload works
- [x] Test automatic updates between beta.1 to beta.2
- [x] Verify code signing
- [x] Update the changelog

Issues blocking release:
- [x] [Linux/Windows] Restart to update doesn't relaunch - remove behaviour in #360, re-add (without bugs) in #361
- [x] [macOS] Could not get code signature for running application - #357, moved to milestone 2.1

**Comment by tomitm** [comment]
Couple of notes on the GitHub release mechanism:
- It'll create a `draft` release when it detects a new version change
  - The draft release is private to maintainers until we publish it
- If there's already a matching release (say beta.1) and it's published as a `pre-release` and we push a new commit to `master`, since the new commit is considered `draft`, it's a type mismatch and won't replace the upload.
  - If we hadn't of published the draft release, it seems like it would've been updated.
- The draft release gets created with a tag name (e.g., `v2.0.0-beta.1` if package.json used `2.0.0-beta.1`), so we don't need to tag the commit ourselves, publishing does that on the latest commit.
  - Unless you want the tag to not be on the latest commit, then diy - but keep the last sub-bullet in mind.

**Comment by tomitm** [comment]
Couple of issues with update to beta 2:

- Found the change for beta.2 (the version number in the footer) in beta.1 somehow. Build logs don't show that change was uploaded to beta.2 (draft/prerelease mismatch) and GitHub's API timestamps don't show it would've been updated. Weird.
- Draft release gets built on tag, but autoupdate detects the tag as a release, and it fails because latest.yml isn't found. The draft release is still private at this point, which includes latest.yml. Need to change the release to publish immediately, or change how the draft release gets created.
- Update results:
  - Linux: Success. There was an error in Sentry about `app-update.yml` not being found, not sure if it's related, but @mitchhentges reported a success.
  - macOS: Partial failure. Errors with "Could not get code signature for running application" but restarting does successfully update.
  - Windows: Shows an update is available, but `download-progress` event never emits, even though the main process logs "Downloading update from [filename]". No error or anything. Restarts to same version.

**Comment by mitchhentges** [comment]
Everything for `2.0.0` looks pretty good, and there's a [2.1 milestone](https://github.com/james-proxy/james/milestone/2) set up for rounding off the edges of the new auto-update system.

I think it's time to pull the trigger for the release.
@tomitm and @nerdbeere, and I get your guys :+1:? At that point, I'll update the changelog and perform the release

**Comment by tomitm** [comment]
Yeah, we've been holding off on releasing this long enough. 👍

We've confirmed auto-update does work, even though it's a bit rough around the corners, it's close enough that we can release and iterate on. Just needs minor fixes, not much to worry about.

🚀

**Comment by nerdbeere** [comment]
Do it 👍

**Comment by mitchhentges** [comment]
Awesome, I'll do the release tomorrow evening :)
Thanks guys! :100: :tada:

**Comment by mitchhentges** [comment]
[`2.0.0` released!](https://github.com/james-proxy/james/releases/tag/v2.0.0)
