### ISSUE TITLE
Safari on OSX does not Proxy

### ISSUE THREAD

**Issue by avboy72** [james-proxy/james#365]
OSX 10.13.2
Safari 11.0.2

After launching Safari from James, Nothing shows up in James when doing HTTP requests in Safari.  No errors are reported in James

**Comment by avboy72** [comment]
James 1.5.0

**Comment by mitchhentges** [comment]
Hey, thanks for the bug reports!
Some browsers support being programmatically attached to a proxy and launched (e.g.: Chrome and Firefox), but other browsers _require_ the user to manually configure the proxy outside of James.

Unfortunately, Safari doesn't support that programmatic-proxy-configuration. We're planning on making it more obvious which browsers work out-of-box, and which ones require additional work by the user: #333.

I'm going to close this issue, but please re-open if I misunderstood it 😄
