### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [james-proxy/james#370]
Hi, I want to design a new logo for the project completely free...

**Comment by mitchhentges** [comment]
Hi @Arslanshn I really appreciate the new logo! Unfortunately, we're applying a ["Material Design"](https://material.io/guidelines/) style of theme to our application, and I don't think that the logo really fits in in that regard.

Thanks again for the logo, though, it's appreciated :smile:

**Comment by Arslanshn** [comment]
hi I am making corrections :)

**Comment by Arslanshn** [comment]
https://drive.google.com/drive/folders/16JGdP3-6yMGijOzuxj77cfOfcmqe4TW5?usp=sharing
