### ISSUE TITLE
Add error messages to 'URL mappings' component

### ISSUE THREAD

**Issue by jrmykolyn** [james-proxy/james#373]
**Proposal:**
Add error messages to 'URL mappings' component.

**Overview:**
Currently, submitting an empty input field will not allow users to proceed from the 'source' to 'destination' steps of the URL mapping process. However, the UI does not provide any information about *why* the user is unable to proceed.

If you're interested, I've completed a first pass of this feature and submitted it for review via PR #374 . I'd be happy to receive feedback/direction re: how to get it approved.

**Comment by jrmykolyn** [comment]
👋 @mitchhentges What do you think about the implementation, and the feature in general?

**Comment by mitchhentges** [comment]
Hey, sorry, thanks for the PR, and I'm excited to take a look, hopefully this weekend!
Work has me busy these days, but it'll be awesome to check it out soon :smile:

**Comment by jrmykolyn** [comment]
Not a problem, and thanks for your consideration!

**Comment by jrmykolyn** [comment]
Merged in via #374. Closing.
