### ISSUE TITLE
Switch back to hoxy

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#382]
Looks like `hoxy` has been [updated to include nerdbeere's crash-fixing patch](https://github.com/greim/hoxy/pull/109).
Until we have any pressing reasons to continue using a fork (e.g. a mandatory patch we need isn't being merged into `hoxy`), I'd like to revert to using `hoxy` again. Is there any reason not to switch back?

**Comment by jrmykolyn** [comment]
@mitchhentges Unless there are other known issues with `hoxy`, this seems like a good idea!

**Comment by nerdbeere** [comment]
Yes, I agree with that and actually wanted to do the same.
I will update #380
