### ISSUE TITLE
James auto-closes itself a few seconds after starting

### ISSUE THREAD

**Issue by beppegg** [james-proxy/james#386]
Hi all,

I downloaded and used James just yesterday using Homebrew, everything went fine. 

Today I just tried to open it again, but after a few seconds, James auto-closes itself. I'm not an ace of MacOS development, so I can't really provide many insights... What I can say is that when I try to launch the program from the terminal, I get the following stacktrace:

```
~ $ /Applications/James.app/Contents/MacOS/James
Loading URL mappings...
Starting proxy...
INFO: proxy listening on 1338
Checking for update
[update status] checking undefined
[xmldom error]	element parse error: Error: invalid tagName:
@#[line:4,col:20]
[xmldom warning]	attribute "CFBundleURLName_" missed value!! "CFBundleURLName_" instead2!!
@#[line:4,col:1069]
[xmldom warning]	attribute "CFBundleURLSchemes]LSHandlerRank^Local" missed value!! "CFBundleURLSchemes]LSHandlerRank^Local" instead2!!
@#[line:4,col:1069]
[xmldom error]	element parse error: Error: invalid attribute:CFBundleURLSchemes]LSHandlerRank^Local
@#[line:4,col:1069]
[xmldom error]	element parse error: Error: invalid tagName:
@#[line:6,col:633]
TypeError: Cannot read property 'nodeName' of null
    at Object.parse (/Applications/James.app/Contents/Resources/app.asar/node_modules/plist/lib/parse.js:68:24)
    at /Applications/James.app/Contents/Resources/app.asar/node_modules/james-browser-launcher/lib/darwin/util.js:23:22
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```
I don't know if it could matter, but my NodeJS version is v10.11.0

**Comment by nerdbeere** [comment]
hey @beppegg! This actually has to do with binary plist files.
We fixed this issue in https://github.com/james-proxy/james-browser-launcher/pull/76

This will be fixed in the next version of james.

**Comment by beppegg** [comment]
Ah, sorry!

I tried to search for a similar issue but I didn't understand that one is related :-P
Is there something I can do while waiting for a new release, in order to get James working?

**Comment by nerdbeere** [comment]
You can clone the master und use that. 
After cloning just run `npm install` and `npm start` and it should work.

**Comment by beppegg** [comment]
Thank you so much!

**Comment by mitchhentges** [comment]
Release `v2.1.0` has been released, so this problem should be solved :smile:
