### ISSUE TITLE
More advanced URL patterns?

### ISSUE THREAD

**Issue by IceHacks** [james-proxy/james#396]
I need to just change the domain but keep the file the same for my redirects.

**How I can do that is:**

```https://mysite.org/js/main.15F6g.js -> https://mybackupsite.org/js/main.15F6g.js```

**How I would like to do that is:**

```https://mysite.org/js/main.*.js -> https://mybackupsite.org/js/main.[1].js```
where `[1]` is the value of the (first) `*` or something like that

**Comment by mitchhentges** [comment]
Hey, thanks for the feature request.
I think we'll be able to solve this with #132 (pull requests always appreciated!)
