### ISSUE TITLE
 Not Found: event-stream@3.3.6

### ISSUE THREAD

**Issue by brykov** [james-proxy/james#397]
Trying to install from freshly cloned repo. After running ```npm install``` I get this:
```
npm ERR! code E404
npm ERR! 404 Not Found: event-stream@3.3.6
```

It seems this version of event-stream package was removed due to some vulnerability.

**Comment by mitchhentges** [comment]
Hey, thanks for the report!
Just set up a little environment on the fly here: I'm using `npm@3.5.2`, and `npm install` on a fresh clone seems to be OK.
Are you still able to reproduce this issue? If yes, what version of `npm` are you using?

**Comment by brykov** [comment]
my node version is 10.14.1, npm 6.4.1 and issue is still there, yes.

**Comment by mitchhentges** [comment]
Thanks for the quick response!
I'm check this out in the next week, just have some alternate plans going on at the moment
