### ISSUE TITLE
Update GitHub demo image

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#59]
It's out-of-date, and doesn't show the "throttle" control. We need to run the 1.3.2 version of James, and get a good screenshot.
@kokarn, maybe you'd be interested?

**Comment by kokarn** [comment]
1.3.2 doesn't include the throttle, right?

**Comment by mitchhentges** [comment]
Hmm, good point. Master has it though, so it depends on whether we want to represent the most-recent-release or current master. @nerdbeere ?

**Comment by nerdbeere** [comment]
For me this doesn't really have high priority. That said, if someone wants to update the screenshot so it represents the latest maser I'm happy to merge it.
