### ISSUE TITLE
Show query parameters as a list in the request detail view

### ISSUE THREAD

**Issue by nerdbeere** [james-proxy/james#62]
They query parameters should be displayed as a list in the request detail view.

**Comment by mitchhentges** [comment]
Opened https://github.com/greim/hoxy/issues/73 on `hoxy`.

**Comment by mitchhentges** [comment]
`greim`, the maintainer of `hoxy`, is fantastic, and [just today added `request.query`](http://greim.github.io/hoxy/#request-query)
