### ISSUE TITLE
Fade out still creates a scrollbar [OSX]

### ISSUE THREAD

**Issue by kokarn** [james-proxy/james#65]
While working on #59 i noticed that the fade out doesn't make the horizontal scrollbar disappear as I believe they should?

Also, I feel the fade starts a bit early. Maybe start it a bit later and fade more aggressively?

![](https://i.imgur.com/FCrjwIy.png)

**Comment by mitchhentges** [comment]
This is occurring on Linux, too, I don't think that it's OSX-specific

**Comment by davidneat** [comment]
@kokarn thank you for the report. I'll update the style to prevent horizontal scrolling.

**Comment by kokarn** [comment]
Thanks! I'll keep posting things I find, no matter how big or small they are :)

**Comment by davidneat** [comment]
@kokarn you're welcome! Thank you for contributing.
