### ISSUE TITLE
v1.4.0-rc1 package doesn't work on Linux

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#81]
I just get a white screen:
![screenshot from 2016-01-29 14-49-49](https://cloud.githubusercontent.com/assets/7784737/12677201/96b4aea2-c697-11e5-9985-50719c9562f5.png)

**Comment by mitchhentges** [comment]
** To reproduce:**
1. `npm run package`
2. `cd package`
3. `electron .` (you might need to `npm install -g electron-prebuilt`)

**Comment by nerdbeere** [comment]
Also doesn't work on OSX

**Comment by nerdbeere** [comment]
Here's the error I get:

<img width="1136" alt="bildschirmfoto 2016-02-01 um 11 25 27" src="https://cloud.githubusercontent.com/assets/423218/12714700/8861dc6c-c8d6-11e5-8c8d-0901334eab9c.png">

**Comment by mitchhentges** [comment]
This should be solved by #82
