### ISSUE TITLE
Chrome Canary, Firefox Dev Edition, etc aren't shown

### ISSUE THREAD

**Issue by tomitm** [james-proxy/james#90]
I have the canary versions of Chrome and Firefox installed. I noticed that `browser-launcher2` does detect them, but gives both browsers the same name.

That also results in React complaining that keys aren't unique:
> Warning: flattenChildren(...): Encountered two children with the same key, `.2:$`. Child keys must be unique; when two children share a key, only the first child will be used.

Not exactly sure which browser version I end up launching at the moment, as the list order seems to change a lot of the time as well.

**Comment by tomitm** [comment]
Couple of options:
- Submit a fix to `browser-launcher2` to identify the names differently (*chrome-canary*), then update James to show the different icons.
- Add an additional logic to look at the path as well. For example, Chrome Canary has *Chrome SxS* in it's path. Seems a bit sketchy, though, as paths are likely not guaranteed.
- Display the browsers in a list instead, showing the name + version number. Even though paths aren't guaranteed, at least version numbers are reliable.

Lemme know which approach you want to take, and I'll implement it.

**Comment by kokarn** [comment]
I'd say try to get browser-launcher2 to identify the names differently.
Should be in their best interest as well.

**Comment by mitchhentges** [comment]
It would be awesome if `browser-launch` was more reliable at showing the browsers. At the same time, I think that putting the browsers in a nice UI list would be cool, too.
![aoz8kgx8pzknypz7z38n](https://cloud.githubusercontent.com/assets/7784737/12713668/483fe062-c8d0-11e5-98cf-d95e1f6d57d5.jpg)

**Comment by tomitm** [comment]
This is fixed with #91.

Also, `browser-launcher` just launches, it's actually [`win-detect-browsers`](https://github.com/vweevers/win-detect-browsers) that does the actual detection. I filed an issue, but it doesn't sound like the author is too keen on the idea, preferring to keep things simple.

So, #91 has a pretty simple check for the browser name based on the command. In that case that the check doesn't manage to figure out the difference, the UI list update does at least show the version, so you can figure it out yourself.

Hope that works out for everyone, lemme know if you have any objections on the PR.

**Comment by mitchhentges** [comment]
It's a little cheesy (SxS for detecting canary?) But it's a definite improvement.
